name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Actualizado a v3 para mejor compatibilidad
        with:
          fetch-depth: 0
          lfs: true # Recomendado para Hugging Face (modelos pesados)

      - name: Check secret presence
        run: |
          if [ -z "${{ secrets.HF }}" ]; then
            echo "EL SECRETO ESTÁ VACÍO"
            exit 1
          else
            echo "El secreto tiene contenido, el problema es la autenticación."
          fi

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          # Usamos -f (force) para asegurar que el Space se actualice con el contenido de GitHub
          git push -f https://braisreal:$HF_TOKEN@huggingface.co/spaces/braisreal/demo main
